version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  backend:
    build: ./backend
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      SECRET_KEY: django-insecure-secret-key
      DEBUG: "True"
      ALLOWED_HOSTS: 127.0.0.1,localhost
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

volumes:
  postgres_data:
